### ISSUE TITLE
Live Demos

### ISSUE THREAD

**Issue by isolin** [Smilebags/spectral-utilities#2]
Hi! None of the live demos is working. All return GitHub 404.

**Comment by Smilebags** [comment]
Thanks for reporting that, I'll try to make some time to fix them up.

**Comment by Smilebags** [comment]
Thanks, they should be working again now!

**Comment by isolin** [comment]
So the demos only work from `github.io` not directly from `github.com`. Replacing relative links in `readme.md` should do the trick. Also the readmes don't work, I suppose it's because of `.md` instead of `.html` :)
